### ISSUE TITLE
Run Api.Write error

### ISSUE THREAD

**Issue by Puzozhitel** [wangziyingwen/AutoApi#1]
![Screenshot_1](https://user-images.githubusercontent.com/60980541/107404007-d90ea400-6b16-11eb-91a8-24b197c53571.png)
How can I fix the error?

**Comment by wangziyingwen** [comment]
我设计的时候，默认e5会有一个自动生成的team，紧接着在里面操作。好像你这里不是？
这种情况，需要看微软的返回值才行，但是需要你配合修改代码。

或者，最简单的，直接把team操作删掉，ApiOfWrite.py文件222行前面加个#号。

**Comment by wangziyingwen** [comment]
已修复 v6.1 （ 需要新加权限group,readwrite.all，以及更新ApiOfWrite.py文件 ）
