### ISSUE TITLE
无法获取token

### ISSUE THREAD

**Issue by wayne0926** [wangziyingwen/AutoApi#11]
按照步骤严格执行。
但是在`● 第一步复制的网址在下面url-code框中填入，点击获取Token。` 时出错。
报错内容：

```
出错 invalid_request:
The request is not valid for the application's 'userAudience' configuration. In order to use /common/ endpoint, the application must not be configured with 'Consumer' as the user audience. The userAudience should be configured with 'All' to use /common/ endpoint.
```
还有，那个页面并没有让我代表组织同意，就直接跳转了，不知道有没有影响

**Comment by wangziyingwen** [comment]
清空浏览器缓存，再试一下。

**Comment by wayne0926** [comment]
> 清空浏览器缓存，再试一下。

索性换了个浏览器登录，还是如此。
使用`rclone`获取同样报错（都是先显示`尝试使你登录`）：
```
我们无法完成你的请求
invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.
```

**Comment by wangziyingwen** [comment]
你注册应用的时候受支持类型选啥啊？看着像选错了
用的啥账号登录啊?

新版不能用rclone，我把重定向换掉了。

**Comment by wayne0926** [comment]
> 你注册应用的时候受支持类型选啥啊？看着像选错了
> 用的啥账号登录啊?
> 
> 新版不能用rclone，我把重定向换掉了。

受支持类型：`个人 Microsoft 帐户用户`

**Comment by wangziyingwen** [comment]
。。。
我又去确认了一遍，个人是第4个吧。
![无标题](https://user-images.githubusercontent.com/21355001/108315283-274a3400-71f6-11eb-8889-90baf9a48513.png)

选最长那个

**Comment by wayne0926** [comment]
> 我又去确认了一遍，个人是第4个吧。

嗯好滴。不过：
![image](https://user-images.githubusercontent.com/63389859/108315358-434dd580-71f6-11eb-83a0-5ce712f316a9.png)

**Comment by wangziyingwen** [comment]
你是不是登错账号了，我试一下私人账号登录是3个

**Comment by wayne0926** [comment]
我这里又出问题了：
在`获取code`并完成授权后，

> 你是不是登错账号了，我试一下私人账号登录是3个

登错账号是指？我好像登录的就是（也只有）管理员账号

**Comment by wangziyingwen** [comment]
申请e5的账号是私人账号
得到的e5账号是组织类型（25人）的管理员账号，可以开子号，所以分为管理员跟子号。

**Comment by wayne0926** [comment]
> 申请e5的账号是私人账号
> 得到的e5账号是组织类型（25人）的管理员账号，可以开子号，所以分为管理员跟子号。

好像明白了：使用`onmicrosoft.com`邮箱登录对吧？
