### ISSUE TITLE
Multiple accounts

### ISSUE THREAD

**Issue by Puzozhitel** [wangziyingwen/AutoApi#13]
Can I add more than one account/app? Earlier there were APP_NUM, CLIENT_ID_2 and other secrets.

**Comment by wangziyingwen** [comment]
add new secret ACCOUNT_ADD can add account,
add new secret ACCOUNT_DEL can delete specified account.
Those secrect will be deleted when the program is finished

**Comment by puzo2** [comment]
> add new secret ACCOUNT_ADD can add account,
> add new secret ACCOUNT_DEL can delete specified account.
> Those secrect will be deleted when the program is finished

So I should add a new secret ACCOUNT_ADD and then run all of the workflows? Or just "Update Token" one?

**Comment by wangziyingwen** [comment]
> > add new secret ACCOUNT_ADD can add account,
> > add new secret ACCOUNT_DEL can delete specified account.
> > Those secrect will be deleted when the program is finished
> 
> So I should add a new secret ACCOUNT_ADD and then run all of the workflows? Or just "Update Token" one?

Both can work,but I did not set the option to manually start one of them.you can only start all programs by clicking star. 
 In addition, accounts can only be added one by one.
