### ISSUE TITLE
获取refresh_token错误

### ISSUE THREAD

**Issue by answer24** [wangziyingwen/AutoApi#15]
出错 invalid_request:
AADSTS50194: Application '99766de6-4537-4c48-b50e-d403fc7c9503'(/github.com/wangziyingwen/AutoApi) is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.

您好，我在使用工具https://wangziyingwen.github.io获取token的时候报错如上，具体可能是什么原因吗？

**Comment by wangziyingwen** [comment]
受支持账户选第三个。。。。

**Comment by answer24** [comment]
> 受支持账户选第三个。。。。

感谢，已跑通，是自己大意了。
