### ISSUE TITLE
获取refresh_token失败

### ISSUE THREAD

**Issue by DarkNight710** [wangziyingwen/AutoApi#16]
点击获取code之后，登陆，授权，报错
Sorry, but we’re having trouble signing you in.

AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'xxb1f654-xxxx-xxxx-xxxx-dade78xxxxxx'.

**Comment by wangziyingwen** [comment]
重定向url不匹配，你自己看看是不是填错了

**Comment by DarkNight710** [comment]
> 重定向url不匹配，你自己看看是不是填错了

不是默认就行么，填http://localhost:53682/是吗？
