### ISSUE TITLE
Update Token 报错

### ISSUE THREAD

**Issue by dantescao** [wangziyingwen/AutoApi#17]
公钥获取成功
账号/应用 1 的微软密钥获取失败
请检查secret里 account_ID , account_SECRET , MS_TOKEN 格式与内容是否正确，然后重新设置
  File "UpdateToken.py", line 140, in <module>
    account['ms_token'][a]=getmstoken(a)
  File "UpdateToken.py", line 82, in getmstoken
    refresh_token = jsontxt['refresh_token']
KeyError: 'refresh_token'
Error: Process completed with exit code 1.

Account ADD Secret里 account_ID , account_SECRET , MS_TOKEN  都是正确的

**Comment by wangziyingwen** [comment]
你是老版升级？重定向url检查一下

**Comment by dantescao** [comment]
谢谢了，Url的问题
