### ISSUE TITLE
一样在run write中出现了此错误

### ISSUE THREAD

**Issue by huang545** [wangziyingwen/AutoApi#2]
第 1 轮

账号 1
上传文件 ( 可能会偶尔出现创建上传失败的情况 ) 
        操作成功
team操作
    获取team
        操作成功
    创建team频道
Error: Process completed with exit code 1.

**Comment by huang545** [comment]
似乎有些时候没有执行team相关操作使其成功，但是只要执行相关操作就会失败

**Comment by wangziyingwen** [comment]
已修复 v6.1 （ 需要新加权限group,readwrite.all，以及更新ApiOfWrite.py文件 ）
