### ISSUE TITLE
Team操作有问题

### ISSUE THREAD

**Issue by yang05051** [wangziyingwen/AutoApi#21]
程序似乎检测不到创建好的Team，因此创建频道和删除Team的操作都无法执行

**Comment by wangziyingwen** [comment]
不用管，权限给够就行。（新版自动给权限，就不用管了）

write的api偶尔会失败，但是大部分时间是能成功的，只能猜是微软的问题。
已经加了失败重试3次，还是不能解决，目前只能让他出错不报错，防止出错邮件通知。
