### ISSUE TITLE
 作者你好，是否可以增加个push代码？

### ISSUE THREAD

**Issue by justincnn** [wangziyingwen/AutoApi#4]
比如tg推送等，这样就知道每次运行的结果，以及是否自当续期，
希望作者可以考量，谢谢啊

**Comment by wangziyingwen** [comment]
tg推送的话，我不清楚tg的模式，要推去哪儿？机器人？而且据我了解，好像有tg的e5续期机器人。

另外，我个人觉得每次的运行结果根本没有看的必要，我们只需要知道运行有没有出错。如果出错，github会发邮件告知（如果是非常用邮箱注册的github，可以设置自动转发到常用邮箱）。
至于是否自动续期。这个无法获取（涉及私人账号）。如果续期了，微软会发邮件告诉你续期了。

**Comment by justincnn** [comment]
> tg推送的话，我不清楚tg的模式，要推去哪儿？机器人？而且据我了解，好像有tg的e5续期机器人。
> 
> 另外，我个人觉得每次的运行结果根本没有看的必要，我们只需要知道运行有没有出错。如果出错，github会发邮件告知（如果是非常用邮箱注册的github，可以设置自动转发到常用邮箱）。
> 至于是否自动续期。这个无法获取（涉及私人账号）。如果续期了，微软会发邮件告诉你续期了。

明白，谢谢作者的仔细解答
