### ISSUE TITLE
v6.1 运行 run api.Write出错

### ISSUE THREAD

**Issue by kanbaopeng** [wangziyingwen/AutoApi#5]
Run python ApiOfWrite.py
Traceback (most recent call last):
账号/应用 1 的微软密钥获取成功
  File "ApiOfWrite.py", line 245, in <module>

    taskWrite(a,'QVQ'+str(random.randint(1,600)))
账号 1
  File "ApiOfWrite.py", line 135, in taskWrite
发送邮件 ( 邮箱单独运行，每次运行只发送一次，防止封号 )
    url=r'https://graph.microsoft.com/v1.0/me/todo/lists

KeyError: 'id'
第 1 轮

账号 1
上传文件 ( 可能会偶尔出现创建上传失败的情况 ) 
        操作成功
task操作
    创建任务列表
        操作失败
    创建任务
Error: Process completed with exit code 1.
![123123123](https://user-images.githubusercontent.com/78746650/107540097-a345ea00-6c00-11eb-9682-c0c8d8d0bdfa.png)

**Comment by yang05051** [comment]
你是不是开启了登陆验证？

**Comment by kanbaopeng** [comment]
> 你是不是开启了登陆验证？

你说的是管理员账号登录的两步验证？Autherticator？？的确开了，我关了再试一试。
另外我用那个稳定版就没问题，一切运行正常。

**Comment by kanbaopeng** [comment]
> 你是不是开启了登陆验证？

找到原因了，你在另外一个回复里说的（需要新加权限group,readwrite.all），我是跟着你最初的教程来的，给漏掉了。
感谢大神！！！
