### ISSUE TITLE
Run Api.Write报错

### ISSUE THREAD

**Issue by vay1314** [wangziyingwen/AutoApi#8]
Run Api.Write报错，请教这个是什么问题？
![QQ截图20210217001513](https://user-images.githubusercontent.com/22141920/108090553-b3087700-70b5-11eb-911e-c8bbbb83d323.png)

**Comment by wangziyingwen** [comment]
这情况不好说，不知道你属于那种。1，api权限没给够；2，微软偶尔抽风，失败了

**Comment by vay1314** [comment]
> 这种情况不好说，不知道你属于那种。1，api权限没给够； 2，微软偶尔抽风，失败了

权限我是按教程一个一个给的，发现你教程更新了，按照你新教程操作一边但卡在获取refresh_token。
"许可接受后会跳转出现空白页面，不用管。"
这步我接受许可后弹出的空白网页，不是 类似 localhost/?code=abc...xyz%session_state=xxx，是下图的地址
![2021-2-17 14-10-37](https://user-images.githubusercontent.com/22141920/108163439-f8ff2280-7129-11eb-9d90-662829f4aff4.png)

**Comment by wangziyingwen** [comment]
直接把网址粘贴进去就行，这句类似不用管

**Comment by wangziyingwen** [comment]
粘进去url-code

**Comment by vay1314** [comment]
> 粘进去url-code

直接这个链接粘进url-code，点击获取是报错了
![QQ截图20210217141942](https://user-images.githubusercontent.com/22141920/108164151-37491180-712b-11eb-8638-c00187cfe7e8.png)

**Comment by vay1314** [comment]
![QQ截图20210217142130](https://user-images.githubusercontent.com/22141920/108164284-75463580-712b-11eb-82dc-19a1db614e8c.png)

**Comment by wangziyingwen** [comment]
看不懂，按理不会出错啊。你的code这么短吗，整个网址复制进去啊

**Comment by vay1314** [comment]
> 看不懂，按理不会出错啊。你的code这么短吗，整个网址复制进去啊

点击授权后出现的空白网页网址，就是这么短的。

**Comment by wangziyingwen** [comment]
那不对，你用的私人账号？

**Comment by vay1314** [comment]
> 那不对，你用的私人账号？

找到问题了，确实浏览器账号没登我的开发者账号，还是默认我的私人账号了。不好意思
